spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: user
    password: secret
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: false
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    open-in-view: false
    generate-ddl: true
  kafka:
    bootstrap-servers: "localhost:${KAFKA_PORT:9092}"
    consumer:
      group-id: "OrderGroup"
    client-id: "OrderApp"
    producer:
      acks: "all"
#    properties:
#      specific.avro.reader: true

schema.registry.url: http://localhost:8081

order-app.kafka.topics-produced:
  - "OrderPlaced"
  - "PlaceOrderRejected"
order-app.kafka.topics-consumed:
  - "OrderSubmitted"
  - "OrderFilled"
