spring:
  kafka:
    properties:
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true
    bootstrap-servers: "localhost:${KAFKA_PORT:9092}"
    consumer:
      group-id: "OrderGroup"
      key-deserializer: "org.apache.kafka.common.serialization.LongDeserializer"
      value-deserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
    client-id: "BillingApp"
